### ISSUE TITLE
Probe endpoint

### ISSUE THREAD

**Issue by surdaft** [damoun/twitch_exporter#83]
**Description**
When using this exporter to be able to gather metrics on many channels at once it becomes cumbersome and would likely lead to a reduced performance at larger loads. I propose adding a probe functionality to the program, similar to how the [blackbox monitor](https://github.com/prometheus/blackbox_exporter) works, where by you provide the endpoint with a target channel and it would query and return the metrics for that channel. This would enable a structure config in prometheus like so:

```yaml
scrape_configs:
  - job_name: 'twitch_exporter'
    metrics_path: /probe
    static_configs:
      - targets:
        - TimTheTatMan
        - JordOfTheNorth
        - LIRIK
```
The benefits of this approach I think would be that it is doing 1 channel at a time, allowing a more concurrent approach to collecting these metrics, since alloy or prometheus would send them concurrently to the probe, and also allowing the config of _who_ to collect to be abstracted from the tool that collects the metrics.

I can look at how to implement this at some point this week, I can also write some documentation up for using it with Alloy or Prometheus.

**Notes:**
- Metrics regarding subscription counts is only available for "self", so a call to `client.GetUsers(&helix.UsersParams{})` may be required to check if this is "me"
